development:
  adapter: mysql
  database: wakame_dcmgr_gui
  host: localhost
  user: wakame_dcmgr_gui
  password: passwd

test:
  adapter: mysql
  database: wakame_dcmgr_gui
  host: localhost
  user: wakame_dcmgr_gui
  password: passwd

production:
  adapter: mysql
  database: wakame_dcmgr_gui
  host: localhost
  user: wakame_dcmgr_gui
  password: passwd
