development:
  adapter: mysql
  database: wakame_dcmgr_gui
  host: localhost
  user: root
  password: 

test:
  adapter: mysql
  database: wakame_dcmgr_gui
  host: localhost
  user: root
  password:

production:
  adapter: mysql
  database: wakame_dcmgr_gui
  host: localhost
  user: root
  password:
