development:
  adapter: mysql
  database: wakame_vdc_isono_api
  host: localhost
  user: wakame
  password: wakame

test:
  adapter: mysql
  database: wakame_vdc_isono_api
  host: localhost
  user: wakame
  password: wakame

production:
  adapter: mysql
  database: wakame_vdc_isono_api
  host: localhost
  user: wakame
  password: wakame
